function downloadYourData() {
  if (radial.value() == 1) {
    if (r21v.value() == r32v.value()) {
      data2Download = [
        ["Inputs:"],
        ["------------------------------"],
        ["Fine: " + fine.value()],
        ["Medium: " +medium.value()],
        ["Coarse: " + coarse.value()],
        ["r21: " + r21v.value()],
        ["r32: " + r32v.value()],
        ["------------------------------"],
        ["Grid Convergence Index Method selected"],
        ["Outputs:"],
        ["------------------------------"],
        [reftype.html()],
        [Rlabel.html()],
        [e21label.html()],
        [e32label.html()],
        [plabel.html()],        
        [fextlabel.html()],
        [deltalabel.html()],
        [uncertaintylabel.html()],
      ];
    } else {
      data2Download = [
        ["Inputs:"],
        ["------------------------------"],
        ["Fine: " + fine.value()],
        ["Medium: " +medium.value()],
        ["Coarse: " + coarse.value()],
        ["r21: " + r21v.value()],
        ["r32: " + r32v.value()],
        ["------------------------------"],
        ["Grid Convergence Index Method selected"],
        ["Outputs:"],
        ["------------------------------"],
        [reftype.html()],
        [Rlabel.html()],
        [e21label.html()],
        [e32label.html()],
        [plabel.html()],        
        [fextlabel.html()],
        [deltalabel.html()],
        [uncertaintylabel.html()],
        [qlabel.html()],
      ];
    }
  } else if (radial.value() == 2) {
    if (r21v.value() == r32v.value()) {
      data2Download = [
        ["Inputs:"],
        ["------------------------------"],
        ["Fine: " + fine.value()],
        ["Medium: " +medium.value()],
        ["Coarse: " + coarse.value()],
        ["r21: " + r21v.value()],
        ["r32: " + r32v.value()],
        ["------------------------------"],
        ["Correction Factor Method selected"],
        ["Outputs:"],
        ["------------------------------"],
        [reftype.html()],
        [Rlabel.html()],
        [e21label.html()],
        [e32label.html()],
        [plabel.html()],        
        [fextlabel.html()],
        [deltalabel.html()],
        [uncertaintylabel.html()],
        [CFlabel.html()],
        [Plabel.html()],
      ];
    } else {
      data2Download = [
        ["Inputs:"],
        ["------------------------------"],
        ["Fine: " + fine.value()],
        ["Medium: " +medium.value()],
        ["Coarse: " + coarse.value()],
        ["r21: " + r21v.value()],
        ["r32: " + r32v.value()],
        ["------------------------------"],
        ["Correction Factor Method selected"],
        ["Outputs:"],
        ["------------------------------"],
        [reftype.html()],
        [Rlabel.html()],
        [e21label.html()],
        [e32label.html()],
        [plabel.html()],        
        [fextlabel.html()],
        [deltalabel.html()],
        [uncertaintylabel.html()],
        [qlabel.html()],
        [CFlabel.html()],
        [Plabel.html()],
      ];
    }
  } else if (radial.value() == 3) {
    if (r21v.value() == r32v.value()) {
      data2Download = [
        ["Inputs:"],
        ["------------------------------"],
        ["Fine: " + fine.value()],
        ["Medium: " +medium.value()],
        ["Coarse: " + coarse.value()],
        ["r21: " + r21v.value()],
        ["r32: " + r32v.value()],
        ["------------------------------"],
        ["FSRE Method selected"],
        ["Outputs:"],
        ["------------------------------"],
        [reftype.html()],
        [Rlabel.html()],
        [e21label.html()],
        [e32label.html()],
                [plabel.html()],
        [fextlabel.html()],
        [deltalabel.html()],
        [uncertaintylabel.html()],
        [CFlabel.html()],
        [Plabel.html()],
      ];
    } else {
      data2Download = [
        ["Inputs:"],
        ["------------------------------"],
        ["Fine: " + fine.value()],
        ["Medium: " +medium.value()],
        ["Coarse: " + coarse.value()],
        ["r21: " + r21v.value()],
        ["r32: " + r32v.value()],
        ["------------------------------"],
        ["FSRE Method selected"],
        ["Outputs:"],
        ["------------------------------"],
        [reftype.html()],
        [Rlabel.html()],
        [e21label.html()],
        [e32label.html()],
        [plabel.html()],
        [fextlabel.html()],
        [deltalabel.html()],
        [uncertaintylabel.html()],
        [qlabel.html()],
        [CFlabel.html()],
        [Plabel.html()],
      ];
    }    
}
save(data2Download, 'data');
}
